### ISSUE TITLE
Support plugin local matrix builds

### ISSUE THREAD

**Issue by thomasf** [drone-plug/drone-plugins-go#2]
This should at least be evaluated during the 0.3 milestone and then maybe postponed to 1.1 when it's known how this feature would interact with other features.. It's not unfeasible to think that this feature could be implemented as an external library.

It would be great if features like this could be provided to plugins without adding explicit support for it by themselves.

```yml
deb:
  image: deb
  matrix:
    - ARCH: amd64
      GOARCH: amd64
    - ARCH: i386
      GOARCH: 386
  arch: $${ARCH}
  files:
    usr/bin/myfile: build/out-$${GOARCH}
```

The API can potentially be something as simple as this:

```go
plugins.Matrix()
```

matrix might also take varadic MatrixOpt funcs so that `plugins.Matrix(plugins.ParallellMatrix(maxworkers int))` can be an expression to enble and limit concurrent execution.
